### PR TITLE
Revert "Remove superfluous argument"

### PR DESCRIPTION
**Pull request by glubsy**
This reverts commit bcb26507fe7f4f0ec555db656c22478494ab5f60.

### CODE REVIEW

**Comment by arsenetar** [comment]
@glubsy, I see you mentioned this fixes a issue with the scanner getting stuck at "Verified X/X Matches" dialog window over at #677.  How were you able to come across the situation, I was not able to get into that state when I checked this before.

**Comment by glubsy** [comment]
To reproduce the issue, I did a scan in "picture mode" and enabled "can mix file kinds" while still having the two test folders in the tested path as mentioned in #676.

To note: this bug also makes python hang and not quite terminate properly, needs a SIGKILL in order to get rid of the process. 
Perhaps this needs further examination and a better fix, but as it is this revert solves the problem so far.

**Comment by arsenetar** [comment]
Did some looking into this with a few different scans again, I am not seeing any issue with the scan hanging for me in Picture mode with that option enabled. I have tried a few folder sets with and without this change I am not seeing any differences in behavior.

Additionally looking around a bit it seems `_create_file` is only called when importing from the saved results xml file so this should not be causing issues during a scan.

I am testing this on windows 10 right now with 64 bit python, but not seeing a reason why this would behave differently between OSes.

**Comment by glubsy** [comment]
Right, it seems the option "match files of different dimensions" is actually what causes the issue for me. Perhaps even when both options are enabled at the same time. Can you reproduce this?

Edit: this is very strange, I cannot reproduce this consistently. It seems almost random.

**Comment by glubsy** [comment]
Yeah it seems his revert doesn't actually fix anything. The problem is somewhere else, and most likely not related to these commits.

**Comment by arsenetar** [comment]
@glubsy, I'll have to play around with the "different dimensions" option turned on to see if I can get it to happen.  Do you mind filling an issue for this so we can keep track of the issue?

**Comment by glubsy** [comment]
Yes I'll have to investigate this further to figure out how to accurately reproduce the issue before filing a bug report.

**Comment by glubsy** [comment]
See #693 .

**Pull request closed without merging**
