### PR TITLE
serialize/deserialize colors to/from bytes instead of strings

### PR DESCRIPTION
**Pull request by Dobatymo**
It's a tiny bit faster, saves a bit of memory and simplifies the code a bit. Also if in the future 3rd party perceptual hashes will be used, it makes saving/restoring to/from numpy arrays even easier (and even faster), since it's only a `.tobytes()` or `.frombuffer()` then.

For benchmarking run
```python
import secrets
from timeit import repeat
from core.pe.cache import string_to_colors
#from core.pe.cache import bytes_to_colors

colorsbytes = secrets.token_bytes(32 * 3)

# assert string_to_colors(colors.hex()) == bytes_to_colors(colors)

print(
    "string_to_colors",
    min(repeat("func(data)", repeat=3, globals={"data": colorsbytes.hex(), "func": string_to_colors})),
)
#print("bytes_to_colors", min(repeat("func(data)", repeat=3, globals={"data": colorsbytes, "func": bytes_to_colors})))
```

### CODE REVIEW

**Review by glubsy — APPROVED** [review]
Have not tested but looks good.

**Comment by Dobatymo** [comment]
Sorry I forgot to mention that this requires users to delete their picture cache. This PR so far doesn't handle old format caches gracefully. Any suggestions?

**Comment by arsenetar** [comment]
@Dobatymo This looks pretty good, I do want to spend some more time actually running this.  With regards to the picture cache, for the sqlite implementation this could do something similar to what has been done with the file cache db to automatically migrate and clear out the db when changes are made see the class at https://github.com/arsenetar/dupeguru/blob/1f1dfa88dc5f6ffe13f4de514c884ab9c83bd7ce/core/fs.py#L96.  For the shelve implementation, it would need a bit different approach, I have been considering removing that back-end anyhow and just doing sqlite only to simplify things but wanted to verify the performance difference between the two before I finalized that decision.

**Comment by arsenetar** [comment]
Merged in changes to resolve a couple minor conflicts from changes I made recently (removing shelve cache, formatting).  Going to be looking at adding a migration to the picture db similar to the other so users don't have to worry about manually clearing cache.

**Comment by Dobatymo** [comment]
Thank you for keep working on my PR :)
I am sorry I don't have any time recently to implement a migration path.

**Comment by arsenetar** [comment]
@Dobatymo No problem, got the changes pulled in here to "migrate" the cache now, will do a bit more testing on my end then merge this as I think it all looks good to go.

**Pull request merged**
