### PR TITLE
Update packaging for 4.0.4

### PR DESCRIPTION
**Pull request by eugenesan**
* Fix main version (Don't use spaces and capitals in versions!)
* Change debian changelog format in hscommon
* Fix build cleanup
* Switch to XZ compression
* Update build instructions
* Build single package for both Debian/Ubuntu
* Update packaging

Requires: https://github.com/hsoft/hscommon/pull/6

### CODE REVIEW

**Comment by eugenesan** [comment]
Ubuntu packages are available at https://launchpad.net/~eugenesan/+archive/ubuntu/ppa/+packages?field.name_filter=dupeguru

**Comment by arsenetar** [comment]
@eugenesan, thanks for the work on this.

Just a few items for clarity:
1. Why is the changelog format being changed?
2. Tell me about reasoning for the change to xz from gzip.
3. Have you tested this packaging with debian?
4. I see you added yourself as a maintainer for the package, do you intend to maintain packages for Ubuntu (ppa) and Debian?

**Comment by eugenesan** [comment]
@arsenetar 
1. Debian/Ubuntu packaging format is usually structured as `{upstream-version}-{distribution-version}~{personal-version}` DupeGuru scripts had the following format: `{upstream-version}~{distribution-release}`, which required minor correction especially since I've modified the script to build a single source package.
2. GZIP considered a very old format and over the years was replaced with BZIP2 and in recent years with XZ (LZMA2), which provides ~40% savings in archives/packages sizes. Majority of distributions (even Windows) switched to XZ quite some time ago.
3. No, I haven't tested on Debian  but I don't see why it wouldn't work. DupeGuru generates only a debian source package and it is a job of distribution maintainers to tweak, test and upload it.
4. It's a normal practice for a package maintainer to add himself to a maintainers list, especially when original maintainer abandoned the project. I was maintaining the package in my PPA for several years and for now, I am planning to continue. I am not a Debian maintainer.

P.S. To add this project to Debian (from where it will be automatically be pulled to Ubuntu), the project's structure must be overhauled.
Currently, the resulting application can't be built from a raw source and requires a "source package generation". Also, it imports external libraries into the tree which isn't a normal practice. Either the libs (hscommon, qlib) are integrated into the project (since no other project actually uses them) or they are packaged separately and dupeguru will depend on them as external packages. In addition, distributions will never accept a package which integrates external python libraries into the source tree since it brings a host of possible security and maintenance issues.
Unfortunately, at least for now, DupeGuru is destined to live in unofficial repos...

**Comment by arsenetar** [comment]
@eugenesan, thanks for the answers.  Since this needs an updated hscommon, I am going to go ahead and pull the two submodules into this project.  (This project is the only one using them any more from what I know, and this was planned for after a complete 4.04 release anyhow.)  I will pull them as they are now.  Once that is done could you update this PR to include the modification to hscommon?

**Comment by arsenetar** [comment]
Looks like I got the submodules pulled into this project successfully.

**Comment by arsenetar** [comment]
@eugenesan Could you add the modification to hscommon to this PR now that it is part of this repo?  If not I will make that change after merging this.  Seemed like it would be nice to keep it together.

**Comment by eugenesan** [comment]
@arsenetar Sorry for the delay, I am mostly offline until next week.
If you won't merge it before, I'll do it next week.

**Pull request merged**
