### PR TITLE
match all orientations

### PR DESCRIPTION
**Pull request by brccabral**
Hi,
I was able to solve the problem with rotated/mirrored images.
Had to add cache blocks for all 8 orientation in the sqlite, but it is working fine.
Let me know if you need any edit.
Cheers,
Bruno

### CODE REVIEW

**Comment by arsenetar** [comment]
I think the general idea here is good.  I do think this should be an option instead of always matching all orientations as some users may not want to match images with different orientations.

**Comment by brccabral** [comment]
> I think the general idea here is good. I do think this should be an option instead of always matching all orientations as some users may not want to match images with different orientations.

Hi @arsenetar , added option for rotated images

**Comment by ne1188** [comment]
This change massively slows down the scan, even when the "match all orientations" option is not enabled. 
The calculation of the blocks for all orientations is always done, predictably slowing down the scan by a factor of 8? or so.

A close to 10x slowdown is too much. I reverted this change on my local copy.

**Comment by glubsy** [comment]
@ne1188 thanks for reporting, please open an issue ticket referencing this PR

**Pull request merged**
