### PR TITLE
Missing renamed regex

### PR DESCRIPTION
**Pull request by glubsy**
* Fix a regex that was missing after a regex rename.
* Fix partial regex match yielding false positive (especially in the exclusion filter dialog window, which showed the test string being matched when in fact it should not match). 
* Fix regex not being cached into the path filters when a directory separator was found in its pattern.

### CODE REVIEW

**Comment by arsenetar** [comment]
Hmm, this one is probably good, wanted to pull down and test, just noticed the tests were not running, fixed that, looks like #910 that I just merged after looking at actually broke tests related to those changes and seems it introduced at least one real bug there.

**Comment by glubsy** [comment]
Woops indeed. forgot to run tox one last time. I'll fix that one in a bit and submit a new PR.

**Comment by arsenetar** [comment]
Well this passed on the linux environments but the test fails in the windows environment https://app.travis-ci.com/github/arsenetar/dupeguru/jobs/528944609.  Yes I merged it thinking it was alright but remembered the Travis tests never ran on this PR due to the issue with Travis when this was created.

**Comment by glubsy** [comment]
Thanks for the heads up. This should be fixed by #927.

**Pull request merged**
